from structural.bridge.abstractions.shape_abstraction import ShapeAbstraction
from structural.bridge.abstractions.square_abstraction import SquareAbstraction
from structural.bridge.abstractions.triangle_abstraction import TriangleAbstraction
